version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `23/8/22`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `23/8/22`
      - mvn package
artifacts:
  paths:
    - '*'
  
