version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mvn compile
      - mvn test
    commands:
      - echo Build started on `23/8/22`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `23/8/22`
artifacts:
  type: zip
  paths:
    - '*'
